### ISSUE TITLE
Утечки памяти

### ISSUE THREAD

**Issue by alexey-malov** [vandb/test#1]
Память, выделяемая в данных методах, при выходе из программы не освобождается.

```
ReadyToMove* ReadyToMove::get()
{
	static auto s = new ReadyToMove;
	return s;
}
```

```
Waiting* Waiting::get()
{
	static auto s = new Waiting;
	return s;
}
```

```
Moving* Moving::get()
{
	static auto s = new Moving;
	return s;
}
```

```
Selecting* Selecting::get()
{
	static auto s = new Selecting;
	return s;
}
```

Совет: установи бесплатный Visual Leak Detector (http://vld.codeplex.com). Очень просто подключается (буквально один ```#include <vld.h>``` добавить в любой .cpp файл). Он при выходе из приложения утечки покажет

В C++ 11 можно синглтон мейерса использовать:
```
Selecting* Selecting::get()
{
	static Selecting state;
	return &s;
}
```
либо вообще без синглтонов обойтись.

**Comment by vandb** [comment]
Исправил. Спасибо
